# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 23:44
from __future__ import unicode_literals

import cms.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('width', models.PositiveIntegerField(verbose_name='Largura')),
                ('height', models.PositiveIntegerField(verbose_name='Altura')),
            ],
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=cms.models.handle_image_file)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cms.Banner', verbose_name='Imagem do Banner')),
            ],
        ),
    ]
