# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 00:07
from __future__ import unicode_literals

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerimage',
            options={'verbose_name': 'Imagem', 'verbose_name_plural': 'Imagens'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='name',
        ),
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(default='a', max_length=255, verbose_name='Titulo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='file',
            field=models.ImageField(upload_to=cms.models.handle_image_file, verbose_name='Imagem'),
        ),
    ]
